### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by Martin1991zab** [Orama-Interactive/Pixelorama#100]
Hi,

it would be nice when everybody could see what is planed for what release aka please use Milestones.

You seam to work on multiple things at the same time, and the actual released version of Pixelorama is 0.5, but you already mentioned that something is planed for a version 0.7 in another issue.

So, (metaphorical question) how long is the way to 0.7 or 1.0?

**Comment by OverloadedOrama** [comment]
Hello. The reason I haven't published any plan is because, while I do have one, it's very messy, filled with a lot of ideas and a very basic schedule which changes all the time. Like you said, I work on multiple things at the same time, which is part of the reason my plan is messy. I guess I could make a `Project` for every future version, where I can put some of the ideas I have for every version. However, I'm a little afraid to do that, because I don't know if I'll be able to implement some of the ideas, or I may find different priorities, and push some features to future versions. I also think `Projects` would work better rather than `Milestones`.

I'll try this and see how it goes, just note that some of the stuff you might see will most likely change. Ideas might get pushed back or even deleted, and a lot more will be added, so it won't be stable.
I'd also like to make a changelog and have it published somewhere on this repository.

As for how long is the way to 0.7 and 1.0, I really can't answer that yet, but 0.6 (which will be the next version) should be coming soon, since most of the features I had in mind are either finished or in progress. Early January 2020 is my estimate.

**Comment by Martin1991zab** [comment]
That is good. Thank you.

(did not know github supports kanban boards, well i guess i had miss a bit of the development)
