### ISSUE TITLE
Dialogs cannot be reopened in the 32-bit Windows version

### ISSUE THREAD

**Issue by novhack** [Orama-Interactive/Pixelorama#1061]
**Pixelorama version:** 1.0 32-bit from Itch.io

**OS/device including version:** Windows 10 64-bit, also supposedly happens on Windows 7 32-bit

**Issue description:**
After Pixelorama starts all dialogs can only be opened once. Any consequential attempt to open the same dialog again will result in a quick darkened overlay flash but the dialog will not open anymore.

Only happens in the Single window mode. If the mode is disabled all dialogs seem to be possible to open.

**Steps to reproduce:**
- Pixelorama 32-bit starts
- Effects > Offset Image dialog can be opened
- Once the dialog is closed it won't be possible to open it again

**Comment by OverloadedOrama** [comment]
The errors are most likely unrelated to the issue and are a result of this Godot bug: https://github.com/godotengine/godot/issues/89657

The issue seems to be that the dialogs open but they immediately close. Enabling exclusive and disabling popup window flags fixes the issue, but also leaving them as is and using Godot 4.3 rc1 fixes the issue as well, at least on my end (tested a Windows 32-bit build with WINE).
