### ISSUE TITLE
Play Animation Does Not Start From Beginning (Or End)

### ISSUE THREAD

**Issue by DoodleGarbage** [Orama-Interactive/Pixelorama#1114]
**Pixelorama version: v1.0.3-stable**

**OS/device including version:**
CPU: 8-core AMD Ryzen 9 6900HS with Radeon Graphics (-MT MCP-)
GPU: Navi 23 [Radeon RX 6650 XT / 6700S / 6800S]
Fedora Linux 40 (KDE Plasma)
Kernel: 6.11.0-666.rog.fc40.x86_64 x86_64 (Fedora 40 custom kernel)
Laptop

**Issue description:**
Actual:
The "Play the animation forward (from beginning to end)" (hotkey f5 by default) plays the animation from the selected frame.
Expected:
The "Play Animation" starts playing the animation from the first frame. Additionally, the backwards version has the same behavior.

**Steps to reproduce:**
Create an animation, of any length of frames. Play the animation (with f5 or the button) while a non-beginning frame is selected. (Alternatively, use the play backwards button to see a similar effect)

**Additional Notes:**
This doesn't look wholly like an unintended feature, and more of a miscommunication from localization. However, having a clearly labeled option that allows playing the animation from the beginning/end would be incredibly useful when working on animations that don't loop, such as an attack or hit effect.

By default, in order to play an animation from the beginning is a two-step process. Being able to play from the beginning at a button's press would be greatly appreciated.

**Comment by Variable-ind** [comment]
Yeah it may be a locale problem as the behavior is intended.
If you want to play from beginning/end there is also a button that moves the current frame to the first frame.

**Comment by OverloadedOrama** [comment]
This behavior is indeed intentional, and I feel like it should stay like this as I think most people would expect the animation to start from the current frame and not from the beginning. I removed the "(from beginning to end)" text in ffc98a4b7f49d147ba50ddc2005d527db6bf16e8 to make the behavior less confusing, so I will go ahead and close this issue now.

I'm personally not against the idea of having some quick way to start an animation from the beginning, but I am worried about adding new buttons that could overwhelm the UI. Ideas are welcome, but should probably done in a separate discussion.
