### ISSUE TITLE
request: suggested features

### ISSUE THREAD

**Issue by drarem** [Orama-Interactive/Pixelorama#16]
Hi, love the tool. I would like to see a few things added/changed/updated:

* Add to the sliders (brush size, onion skin) checkboxes for 1,2,3, and 4. Anything bigger could be added using the slider.
* On adding a new frame, retain the zoom factor instead of zooming out.
* Turn the pencil, eraser, etc buttons into graphical icons and put tooltips over them.
* Default FPS should be 6 or 12 instead of 1 IMO. I do like the fact you can draw while it's animating.
* Don't know if there is a hotkey for moving to the frame and then selecting it automatically for editing, rather than how it is now when using the arrow keys and then hitting enter to edit it.
* Somewhere on top of the selected frame, have three small button overlay popups - delete frame key, clone frame and then insert a new empty frame.

**Comment by OverloadedOrama** [comment]
Hello, thank you for the feedback. A big part of the next version of Pixelorama is going to be a UI overhaul, with icons for the tools, and improvements in general. The UI so far has been let's say... lacking, because I was mostly focused on adding features and because I'm not an artist. For the next version, an artist from my team is going to help me with the UI and it will most likely be improved greatly. That being said, the feedback you provided is deeply appreciated and will be taken into consideration!

I would like some further elaboration, however, on your first suggestion. I'm not entirely sure how checkboxes for 1, 2, 3 and 4 and a slider for bigger values would look like.

**Comment by OverloadedOrama** [comment]
Suggestions 2, 3, 4 and 5 have now been implemented. As for suggestion 6, you can right click the frame and a popup menu with options that include delete frame, clone frame, move left & move right appears. Still unsure what suggestion 1 is, so for now I will close this issue as most suggestions have been implemented.

Thank you!
