### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by OverloadedOrama** [Orama-Interactive/Pixelorama#232]
Recently, I've been thinking of making internal code changes so the project can become easier to understand and to comprehend for people who want to read/study/modify/improve the code. A lot of contributors have shown interest in this idea as well.

The current script structure is a bit odd, there are scripts like `Main.gd` that have a lot of different methods and logic inside of them and it would probably be best if they were split up. Problem is, I'm not entirely sure what the best approach is. Should we leave the overall structure as it is and just break some large scripts into smaller scripts? Should we have each and every thing has its own scripts with their own specific logic inside of them? Should we take a more OOP approach (even though I'm not sure how exactly we can do this)?

So I decided to open this issue to get feedback from you too, and to discuss what exactly is the best course of action to take. If you have any ideas of how the code structure can be improved, feel free to discuss. In case you have a specific structure in mind, I would appreciate if you were as analytical as possible and if you provided specific steps with examples of what the best course of action may be.

**Comment by novhack** [comment]
We already discussed this on Discord a bit but my suggestions would be:
- Mainly separate bigger scenes into smaller ones to avoid as many merge conflicts as possible.
- Cut bigger scripts into smaller ones - Canvas.gd for instance is a good candidate and just moving _tools_ code into something like `Tools.gd` would help readability a lot.
- If it's possible - move functionality away from UI scripts. I think that UI scripts should mostly contain only callbacks for UI signals and init/ready code. An example can be _save functionality_ where UI callbacks call functions from `OpenSave.gd` script.
- Some scripts contain big functions which could be also separated into smaller ones - this could also remove some duplicite code.
- The whole Godot is OOP by default because _scripts_ are handled like objects so I don't think there is a need to do more on that front unless it helps with duplicite code (like if some scripts contain same code that could be inherited from a shared class).

**Comment by OverloadedOrama** [comment]
Progress so far:

- [x] Cut `Main.tscn` into smaller scenes, like `UI.tscn` (which is also consisted of smaller scenes), `TopMenuContainer.tscn`, Brushes & Patterns popup scenes and Open/Save Sprite scenes. `Main.tscn` used to have 1951 lines before the refactoring branch, now it has been reduced to just 139.
- [x] Split `Main.gd` into smaller scripts like `ToolButtons.gd` and `ColorAndToolOptions.gd`, where all the tool options are. The options themselves were also refactored to have less duplicate code for left & right. On the same topic, most variables in `Global.gd` that were for left & right were merged into one array with 2 values. Slot 0 for left, slot 1 for right. Also, see #243 and #244 
- [x] Instead of using strings for comparisons, enums are being used instead. This let me handle left and right variables as arrays, like I mentioned above. It also may result in a slight performance boost too, since comparing integers is a lot cheaper than comparing strings.
- [x] Split `PreferencesDialog.gd` to `HandleLanguages.gd`, `HandleThemes.gd` and `HandleShortcuts.gd`. I think this makes the code inside the Preferences much cleaner. Preferences were further refactored in #251.
- [x] Created `DrawingAlgos.gd` (an autoloaded script), where all heavy drawing algorithms are being housed. Drawing methods from `Canvas.gd` and `Global.gd` were moved there. As a result, `Canvas,gd` is a lot easier on the eyes now, so I'm not sure if `Tools.gd` is needed now. I did create a `handle_tools()` method to take some code away from `_input()`.
Another reason I made `DrawingAlgos.gd` is to have all the expensive algorithms in one place, so it will be easier for them to be converted to GDNative in the future. If there are disagreements over this, or perhaps you feel that `DrawingAlgos.gd` should be split to even more scripts, let me know!
- [x] Not a huge change, but I added ignore comments to the warnings. They seem trivial anyway, and they took unnecessary space from the Debugger console.

All in all, I am happy with the results so far. The amount of code has been reduced without features being lost, and it is now hopefully cleaner to read and digest. Especially the `draw_brush()` method that used to be in `Canvas.gd` and is now in `DrawingAlgos.gd`. To any poor souls who attempted to read that method, my apologies. Hopefully now it's better!

I'm not sure if there's anything left to do. I'll take another look in the code to see if there are more stuff that need to be improved. Let me know if any of you have any more refactoring suggestions!

**Comment by jegor377** [comment]
I think that we should use enums instead of numbers in certain tables (instead of something like layers[some number specific to section][actual iterator] to be layers[CANVAS][i] or to be just layers[i].canvas. This is not literal example from code but I've seen something similar) from Global.gd or just change those variables (that hold complicated structures as tables) to be classes.

**Comment by OverloadedOrama** [comment]
@jegor377 That's a brilliant idea! I wonder why I didn't think of using classes instead of making a mess out of nested arrays. I'll work on that next.

**Comment by OverloadedOrama** [comment]
All right, I created classes for Layers, Cels and Animation Tags that replace the nested array mess. It seems to be working, although I haven't tested it very carefully yet, so there may be some crashes. If there are no other requests, I'll test the changes more, merge them into master and close this issue.

**Comment by Kinwailo** [comment]
I think west_limit, east_limit, north_limit and south_limit should rename to x_min, x_max, y_min, y_max, it is more common and easy to understand.

**Comment by OverloadedOrama** [comment]
Done. These variables will most likely go away in the future though, when we enhance the selection system and add more selection tools. Probably for v0.9.
