### ISSUE TITLE
Suggestion: Don't change frames in drawing area while animation is playing

### ISSUE THREAD

**Issue by novhack** [Orama-Interactive/Pixelorama#25]
Currently frames change in the drawing area when you play an animation so you can draw in motion. It is not possible to select a single frame and edit it while playing the animation in a preview to see how it's changes affect the animation.

**Comment by OverloadedOrama** [comment]
The main reason that this happens is to let the user draw while animating. Having the animation play in a preview area and not in the canvas area would destroy this functionality, so it's not going to happen. However, I do understand the problem and I agree that this functionality should be editable. I don't know if I'll be able to do this in the next version because I'm already too busy with UI changes, but I will definitely focus on making some things toggle-able in the future, and "motion drawing" will be one of them.

Of course, pull requests are always welcome if anyone wants to contribute!

**Comment by OverloadedOrama** [comment]
It's been a while, but I haven't forgotten about this suggestion. I've been thinking of adding an extra "play" button in the small canvas preview on the right. It looks something like this:
![image](https://user-images.githubusercontent.com/35376950/89111142-cfff9480-d45a-11ea-918e-ff342f778c13.png)
That play button plays the animation only on the preview space and not on the main canvas, which means you can draw on a single frame while previewing the animation at the same time. The main play button remains unchanged, if it's pressed, the animation plays everywhere.

Is this solution good enough for the suggestion?

**Comment by novhack** [comment]
I think it's pretty cool. Thank you. :)
