### ISSUE TITLE
Feature: Color picker with HSL

### ISSUE THREAD

**Issue by novhack** [Orama-Interactive/Pixelorama#26]
The color picker that is currently in Godot doesn't have HSL color selection.
I suggest creating a custom color picker that includes this feature.
As a bonus it could maybe bypass #10 but that is not guaranteed.

This is how color picker looks in Pyxel Edit as a reference (the shading part on the right could be an inspiration for the future 😄):
![picker](https://user-images.githubusercontent.com/42614907/69526247-10bd1a80-0f6a-11ea-9055-879eac02c4cd.png)

**Comment by OverloadedOrama** [comment]
This is an interesting suggestion. I already plan to make a custom color picker since Godot's can be a little... problematic and weird. So I'll keep this in mind. But right now I'm focused more on improving the UI and adding more functionality so Pixelorama becomes more usable. So, unless someone wants to contribute in making a custom color picker, this may take some time to get done and will most likely not happen in the next couple of versions.

**Comment by Calinou** [comment]
Doesn't the ColorPicker in Godot 3.2beta already offer this?

**Comment by OverloadedOrama** [comment]
> Doesn't the ColorPicker in Godot 3.2beta already offer this?

To be honest I haven't worked with 3.2beta at all as of right now. I'm waiting for it to become stable so I can port Pixelorama to 3.2 without problems.
