### ISSUE TITLE
0.7 Download is claimed to be damaged (Mac OS Mojave)

### ISSUE THREAD

**Issue by VGBoy** [Orama-Interactive/Pixelorama#264]
I tried opening up the Mac version, but it gives me this error message.
<img width="415" alt="Screen Shot 2020-06-18 at 1 54 02 PM" src="https://user-images.githubusercontent.com/18492821/85055267-49714b00-b16b-11ea-8c39-9c888c081899.png">
It doesn't make sense since previous versions opened up just fine.

**Comment by Schweini07** [comment]
Related to #261?

**Comment by VGBoy** [comment]
No. I downloaded the 0.7 version and tried opening right after taking it out of the ZIP. There's no brief flash of the menu, just the error message above. The 0.6 version I can still launch without issue, and it doesn't crash at the menu in 0.6.

**Comment by VGBoy** [comment]
The Mac download for 0.6.2 also appears to be claimed as damaged by the Computer.

**Comment by OverloadedOrama** [comment]
This is most likely a duplicate to #240. Try and follow these instructions found in itch.io's download page (I put them in GitHub Releases now too)

"You may encounter some errors saying that Pixelorama is damaged. This is because the latest versions of MacOS mark the launcher of unknown binaries as a non-executable file. This most likely has to do with the fact that Pixelorama is not signed.

After you extract the .zip file, right-click on the .app file >choose Open in the dropdown then click Open in the warning dialog. Alternatively, you can right click the .app > show package contents, then open a terminal inside its Contents/MacOS folder. Then, type chmod +x Pixelorama . Go back to the .app file and you can now open it normally."

**Comment by VGBoy** [comment]
The chmod +x method doesn't work.

**Comment by OverloadedOrama** [comment]
Unfortunately, there is not much we can do. We can't offer a .dmg build of Pixelorama because we don't own a Mac. Our only hope is to either find another method, or to hope that Apple learns to treat developers better and not make their life harder.

**Comment by wyattbiker** [comment]
@VGBoy Where did you download it from?  And how did you try to run it?

**Comment by VGBoy** [comment]
It was from the Github Releases. I first tried opening it normally by clicking on the .app, and it gave the "damaged" error. I then went into the package contents and followed the instructions of using chmod +x on the Contents/MacOS/Pixelorama. Didn't return anything, so I assumed it worked. Tried opening it up by clicking on the .app again, but it still gives the "damaged" error.

**Comment by saluk** [comment]
I'm getting the same issue on Catalina. Even with chmod +x, and running the executable from inside the .app folder osx says the file is damaged. 
I tried a different tack - downloading and running from the itch app, which I've seen as a workaround for getting itch software to run in the increasingly difficult apple environment. The app was then able to run but had a stack trace.
<img width="996" alt="image" src="https://user-images.githubusercontent.com/54372/86429352-2636b780-bca4-11ea-9356-bfea328b679d.png">

Final workaround - navigating in the Pixelorama.app that itchio downloaded (/Library/Application Support/itch/apps/pixelorama/Pixelorama.app/Contents/MacOS), and the running "open Pixelorama". That seemed to actually open the app - no clue why.

**Comment by Calinou** [comment]
I made a website to assist in bypassing macOS' Gatekeeper: https://disable-gatekeeper.github.io/

Bookmark away :slightly_smiling_face:

**Comment by emersonthis** [comment]
I'm on MacOS 10.15.6 and getting the same messages described above even after disabling gatekeeper using `sudo spctl --master-disable`.

**Comment by OverloadedOrama** [comment]
Since v0.8, we are using GitHub Actions to generate .dmg binaries for macOS, which should have execute permissions by default. Apart from that, you also need to disable Gatekeeper (https://disable-gatekeeper.github.io/), as Pixelorama is not a signed app, and it most likely won't be for the foreseeable future, as this requires $99 annual payments to Apple. So I'll go ahead and close this issue now.
