### ISSUE TITLE
Importing Image to New Layer

### ISSUE THREAD

**Issue by CursedDrag0n** [Orama-Interactive/Pixelorama#279]
I'm working on a project right now where I created two different images and needed to layer one on top of the other (one a 1080 x 720 and the other a 250 x 50). I thought I could do them on two separate project files, then put them together but anytime I tried it it only put it into a new frame. And I couldn't take it from that frame to a new layer either. It'd be a fairly useful feature to have, importing images onto a new layer.

**Comment by OverloadedOrama** [comment]
Importing images as layers has already been implemented in the main branch (v0.8-dev) and will be included in the final v0.8 release. In order to keep the size of all frames and layers the same, the imported image gets cropped to the project's size. For example, if you are working on a 32x32 project and you're trying to import a 250x250 image as a new layer (or a new frame), the imported image will get cropped to 250x250. Should we give more options to the user, like choosing which part of the image will be cropped?

I assume you want to use the 1080x720 image as a reference image. I am thinking of providing the option of importing an image as a reference layer. The reference layer will be of any size you want, but, like the name says, you won't be able to draw on it or export it, it will only be used as a reference to help the artist. Does this sound good?

**Comment by 20kdc** [comment]
This issue was closed as completed, but I'm not sure where the reference image functionality actually is.
I have a prototype of such functionality available and will be trying to clean up the issues ready for a PR shortly, though I'll probably need some help to clean up the code to better match various elements of Pixelorama's design.
If I'm simply confused and the functionality already existed all along, do you mind directing me to it?

**Comment by OverloadedOrama** [comment]
This issue was closed because importing images to new layers is already possible. To do that, you can either go to the File menu, select Open and select the file you want to import, or simply drag and drop it into Pixelorama. A dialog will appear with import options. In the import as option button, select "New layer". However, this crops the imported image to the size of the project, so it doesn't work well for reference images.

Reference images have not been implemented yet. That feature is being tracked in another discussion, #565.
