### ISSUE TITLE
Frame Tag stuck at 100 frame

### ISSUE THREAD

**Issue by fian46** [Orama-Interactive/Pixelorama#403]
**Pixelorama version:**0.8.1

**OS/device including version:**linux mint 20

**Issue description:**frame tag can't tag more than 100 frame animation

**Steps to reproduce:** -

**Comment by Schweini07** [comment]
This is because the maximum value from the `ToSpinBox` node in the `FrameTagDialog.tscn` scene is set to the default which is 100.
![image](https://user-images.githubusercontent.com/47503977/103087872-3b542980-45e9-11eb-9939-e55982a403ca.png)
We could either set the value to something higher or limit the max value to the number of frames existing.

**Comment by fian46** [comment]
I think you can check allow greater to allow higher number entered. Can someone do that ?
