### ISSUE TITLE
Crash when reloading more than one backuped empty project

### ISSUE THREAD

**Issue by kleonc** [Orama-Interactive/Pixelorama#445]
**Pixelorama version:** [4001a32f2b2badc3cd31cd49e09ebbf4d8378473](https://github.com/Orama-Interactive/Pixelorama/tree/4001a32f2b2badc3cd31cd49e09ebbf4d8378473)

**Issue description:** Title.
Seems like `OpenSave`'s member arrays: `current_save_paths` and `backup_save_paths` are assumed to be the same size as arguments passed to the `OpenSave.reload_backup_file` method which seems to not always be the case.
![Godot_v3 2 3-stable_win64_7pmZsbo1A5](https://user-images.githubusercontent.com/9283098/106285066-4d5a6500-6244-11eb-9eb5-b5f9ed6ac7a2.png)

**Steps to reproduce:**

1. Create at least 2 empty projects (with nothing being drawn) and wait for each of them be autosaved.
2. Terminate the program (for example by clicking stop button in the Godot). Closing Pixelorama with the X button seems to not cause the crash.
3. Run Pixelorama again and confirm reloading backups.

**Comment by OverloadedOrama** [comment]
Seems like the issue happens because importing a new project when the current one is empty, replaces the empty project instead of creating a new tab. This behavior happens when importing backups too, the first project is empty, so the second one replaces it, thus a new value is not being appended in `backup_save_paths[]`, which results in the error. It should get fixed in the next commit.
