### ISSUE TITLE
Allow users to resize PalettePanel y.size to zero to make is consistent with ToolSettingPanel.

### ISSUE THREAD

**Issue by yuyutsupoudel** [Orama-Interactive/Pixelorama#497]
**Pixelorama version:**

latest

**OS/device including version:**

popos

**Issue description:**

can drag tool setting window to zero to expand palette window to maximum but can not do vice versa. 
If user can expand palette window to take full space, user should also be able to expand tool setting windows to maximum.

**Steps to reproduce:**
https://user-images.githubusercontent.com/49397015/122625306-3e296600-d0c4-11eb-9e0b-1209e6d1f3d8.mp4

**Comment by OverloadedOrama** [comment]
I marked this as closes in #761 because, even though it doesn't allow make the palette panel get resized to 0, it is now possible to resize it to a smaller height than the palette's height. Most panels in the UI cannot get resized to 0 anyway. If this is a desirable feature, perhaps a general proposal for all panels to get resized to 0 (and therefore hidden) will be needed. For now, if you want to hide a panel completely, you can go to the Window menu, Panels, and uncheck the panel you want to hide.
