### ISSUE TITLE
Blended brush not drawing as blended

### ISSUE THREAD

**Issue by SbNanduri** [Orama-Interactive/Pixelorama#51]
Is it just me or is the transparent part of the blended brush being drawn as the same solid colour as the rest of the brush?

![image](https://user-images.githubusercontent.com/39013190/70869318-ac352000-1f57-11ea-8911-d5ac2463f784.png)

**Comment by OverloadedOrama** [comment]
You can choose where the custom brushes get their color from, under the brush size where it says "Brush color from". If set to 1, then all of the color will be taken from the selected color. If set to 0, then the brush color will not be affected at all from the selected color. This is because it's possible for some custom brushes to have multiple colors and not be just plain black.

Now, this does cause issues when alpha comes into play. If "brush color from" is set to 1, then the color fully comes from the selected color, and all alpha values get lost. If set to 0, the brush keeps its alpha, but it will always be black.

I'm not entirely sure what is the best way to handle this. If anyone has any ideas, feel free to let us know!

**Comment by SbNanduri** [comment]
Thanks for the timely response, and I tried setting that 'brush color from' value to something less than 1, and the brush appears with the proper transparency, but when I click to apply it, no transparency is applied.

**Comment by OverloadedOrama** [comment]
That's because the mouse click happens for multiple frames, so the brush gets drawn over and over and it appears opaque. To fix this we need a way to make custom brushes get drawn only once at a time. I will try and fix this soon.

**Comment by SbNanduri** [comment]
That makes sense, thanks.
I also noticed something else with transparency. If I select the one pixel brush and choose a transparent colour, it replaces the colour on the current layer as you draw over it instead of overlaying the transparent colour on top. Is this intended?

**Comment by OverloadedOrama** [comment]
I'd say that this is intended yes, If you want to draw over it you could use another layer. If you, or anyone, thinks that this shouldn't happen, feel free to discuss about it. Personally I think it makes sense, but I'm not that much of an artist myself so I can't be sure that this behavior is the best.
