### ISSUE TITLE
Details report in version 0.9 [on Windows 10]

### ISSUE THREAD

**Issue by xavierocampos** [Orama-Interactive/Pixelorama#536]
They are small bugs, but I wanted to repot them anyway to give you a hand.I had already made a video about Pixelorama https://youtu.be/ZNU4JheAT2g so you know that I am Spanish speaking, well in the new selection tools when I position the mouse over it I get the name "Bote de pintura" (which refers to the paint bucket) instead of showing me the name of the selection tool, for example "Selección rectangular" or "Selección elíptica", I collaborate in Godot translating the interface to Spanish so if you have any questions about how to call any tool you can ask me and I will gladly help you, because I love and praise your project.

Another detail is that in Windows 10 when I anchor the program to the start menu I get the Godot logo, this did not happen with the previous version that respected the Pixelorama logo.

Greetings and thanks for the great work you are doing. 🤟

**Comment by OverloadedOrama** [comment]
Hello! I pushed a hotfix for the issue with the icon. If you download it again, it should display Pixelorama's icon now instead of Godot's. If you still see the Godot icon, try moving Pixelorama and its files to a different folder. I apologize for the issue.

As for the translation issue, it seems like the Spanish translation is incomplete. If you'd like to add new translations or suggest changes to existing ones, you can use Crowdin for this. https://crowdin.com/project/pixelorama/es-ES

Thank you for the kind words, really appreciated!

**Comment by xavierocampos** [comment]
The icon has been fixed, I'll take a look at the translation strings right away. 🤟

**Comment by OverloadedOrama** [comment]
All right, thank you! The translations will be updated before the next version comes, so I'll go ahead and close this issue.
