### ISSUE TITLE
failed to run pixelorama from godot

### ISSUE THREAD

**Issue by 2439905184** [Orama-Interactive/Pixelorama#701]
**Pixelorama version:**

just 
![image](https://user-images.githubusercontent.com/29478722/168207308-0d21d701-851b-4881-851f-6e7e900b98c6.png)

**OS/device including version:**

![image](https://user-images.githubusercontent.com/29478722/168207283-0251f066-4977-4e86-a387-89ec2f69da07.png)

**Issue description:**

failed to run pixelorama from godot
![image](https://user-images.githubusercontent.com/29478722/168207379-8ae284b8-f81a-4759-bb55-a650fce35718.png)
![image](https://user-images.githubusercontent.com/29478722/168207537-b00e2bd3-9c1c-4b19-be3d-2d5da9802807.png)
just follow this :
![image](https://user-images.githubusercontent.com/29478722/168207640-94c878ba-3e52-4dce-849e-b89ab685e00b.png)

**Steps to reproduce:**
click run button to run it.
![image](https://user-images.githubusercontent.com/29478722/168207345-266c0ecd-4bac-41fd-817b-183235a19640.png)

**Comment by OverloadedOrama** [comment]
I assume it's because of this https://github.com/godotengine/godot/pull/49983, Godot may not be able to open .gdshader files in versions prior 3.3.3. Try running Pixelorama from Godot's latest version instead, 3.4.4. I updated Pixelorama's "Compiling from Source" page to mention Godot 3.4 to avoid confusion.
