### ISSUE TITLE
CPU load in the flatpak version

### ISSUE THREAD

**Issue by Smoon8P** [Orama-Interactive/Pixelorama#809]
**Pixelorama version:** 
0.10.3-stable

**OS/device including version:** 
Linux Mint 21.1, Cinnamon 5.6.5, linux 5.15.0-57-generic
cpu: AMD Ryzen 9 5900X 12-Core
gpu: AMD Radeon RX 570
Flatpak 1.12.7

**Issue description:**

When the application starts, one core is loaded to 100%. The load is on for the entire time the application is on. The problem is only with the flatpack version. If I use the version from tar.gz there is no problem with the cpu.

In htop it is a process: /app/bin/godot-runner --audio-driver Dummy --main-pack /app/bin/pixelorama.pck
In the listing (--verbose) there is no difference between the version from flatpak or from tar.gz.

**Steps to reproduce:**
After every start.

**Comment by Zireael07** [comment]
Likely same as Godot engine issue https://github.com/godotengine/godot/issues/67355

**Comment by OverloadedOrama** [comment]
Is this still reproducible with v0.11? This version was built using Godot 3.5.2, which should have fixed this issue.

**Comment by OverloadedOrama** [comment]
I indeed could replicate it with v0.11, but not with v0.11.1 which came out today. Most likely because now [org.godotengine.BaseApp uses Godot 3.5.2](https://github.com/flathub/org.godotengine.godot.BaseApp/commit/9365b7c3ac9475ff42e21f5f2eb4dcaa4deac31e). So I think this issue should be considered solved now.
