### ISSUE TITLE
The undo/redo system consumes a lot of RAM

### ISSUE THREAD

**Issue by OverloadedOrama** [Orama-Interactive/Pixelorama#883]
**Pixelorama version:**
v0.11.1-dev, happens in all previous versions as well

**OS/device including version:**
opneSUSE Tumbleweed, but occurs on all operating systems and hardware

**Issue description:**
The undo/redo system stores each change the user makes to the cel data (by drawing, applying effects etc) as separate `Image`objects for each undo state. For example, let's say we have a 6400x6400 project with a single cel. This alone consumes 6400x6400x4 ~= 163.84MB of memory. Drawing a single pixel, will store another 6400x6400 to memory via the undo/redo system, thus increasing the memory usage with another ~163MB. This is extremely inefficient, since only a single pixel has been changed. A workaround to clear the undo history is to either close and restart Pixelorama, or close that project, and the memory will be freed.

Ideas and proposals on how the system can be improved are welcome!

**Steps to reproduce:**
Follow the example above, and have a system activity/task manager utility open to measure Pixelorama's memory usage.

**Comment by AlphinAlbukhari** [comment]
An idea that comes to my mind is by writing the undo history into a file
For example, for every 20 step, we'll save our previous history into a file then clear our undo history in memory. If the user is undoing and trying to access the freed history, we will read and load that saved history

**Comment by MatteoPiovanelli-Laser** [comment]
Launching pixelorama from the godot editor, my test: on a 6400x6400 canvas, draw 10 separate (more or less) vertical lines with the pencil tool at thickness 50.
Screenshot with the Windows Resource Monitor to show the used memory.

Code from master branch: 2+GB
![image](https://github.com/Orama-Interactive/Pixelorama/assets/19283945/55d66193-b37c-46e9-b29a-415920e3e22f)

Code from my proposal: around 600MB
![image](https://github.com/Orama-Interactive/Pixelorama/assets/19283945/a14305f2-910c-44cc-a364-20e047097321)

The trick is compressing the hex data in the image, and decompressing it when that "state" needs to be restored.
I only applied this to https://github.com/Orama-Interactive/Pixelorama/blob/e195e32e007743b253c446e9a11acd86a17050c9/src/Tools/Draw.gd#L201 , because I don't know the other operations that may be affected by do/undo enough to claim the same principle should apply. Moreover, I did not try to optimize this further: for example, I only used the default compression method.

Other specific do/undo operations could be clever, and track the methods they should apply, at least in the "do" direction, rather than storing the entire images.

**Comment by OverloadedOrama** [comment]
Continuing from the initial work made in #890:
e62548517f4d976bdcf8e6ade3c7fa684ae1d865 - compresses image data of image effects, bucket tool and selection transformations.
4f5f37a52286cb68899e29d6505ebe065d4880f5 - does not store image data of the move tool, just a difference vector and on undo/redo just move the pixels of the image based on that vector
e22794e61180a0ad7ffc018758b0308f87713365 - compresses image data of the mirror image effect
9279a8e0ab8eb06c392e61badb064b9984b4a4f3 - compresses image data of scaling and centering (in DrawingAlgos.gd)
2c5ece53ddcbc091f0421981d401633b55098635 - compresses image data of replacing cels (when importing an image) and merging down layers.
e6d53292546511a208d9cade104efda4ef143f9c - compresses the image data of the selections themselves (since they are stored as images)

With all these optimizations, I think this issue can be considered resolved now. The next big RAM optimization that could be done is that empty cels still consume a lot of memory. Not entirely sure how this can be solved though, perhaps by dynamically rescaling images based on how many pixels are drawn. This system could theoretically allow for layers with different sizes, but that's a discussion for another issue.

A negative side effect coming from saving compressed image data in undo/redo is that drawing on large canvases is noticeably laggier, talking about sizes like 6400x6400, at least on my machine. Perhaps a better way can be found that is both not so CPU intensive and also consumes less RAM, but again, that's probably a discussion for another issue.

These changes I made are for the v1.0 branch, but I will also port them to v0.11.4 soon.
